# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-05 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=20, verbose_name='作者名称')),
                ('agender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='性别')),
                ('acomment', models.CharField(max_length=200, null=True, verbose_name='描述信息')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name_plural': '作者',
                'db_table': 'tb_authors',
                'verbose_name': '作者',
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branking', models.SmallIntegerField(verbose_name='排名')),
                ('btitle', models.CharField(max_length=20, verbose_name='名称')),
                ('bauthor', models.CharField(max_length=20, verbose_name='作者')),
                ('btype', models.CharField(max_length=20, verbose_name='分类')),
                ('bread', models.IntegerField(default=0, verbose_name='阅读量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name_plural': '图书',
                'db_table': 'tb_books',
                'verbose_name': '图书',
            },
        ),
        migrations.AddField(
            model_name='authorsinfo',
            name='abook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookInfo', verbose_name='图书'),
        ),
    ]
